apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-server
  name: my-server
spec:
  selector:
    app: my-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
